server:
  port: 9999

spring:
  config:
    activate:
      on-profile: local
  # mail서비스 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: daeunk71@gmail.com
    password: jbyxiflyjkwjnsgb
    properties:
      mail:
        smtp:
          auth: true                        # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정해야 한다.
          starttls: # SMTP 서버에 TLS를 사용할 것인지 여부를 지정한다. Gmail SMTP 서버는 TLS를 사용해야 하기 때문에 true로 설정해야 한다.
            enable: true

      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분 이메일 인증 코드의 만료 시간(Millisecond)


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  # Replication 설정 -> hikari와 jdbc-url을 사용하면 된다!
  datasource:
    url: jdbc:mysql://localhost:3306/gentle-dog-vendor # 이부분을 바꿔야함
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        one-indexed-parameters: true
JWT:
  secret-key: fbcb542e08e7feed1c9ebc3740ee092f43304e0b8a666d63bc36fbe785ad447a
  #  expiration-time: 14400000
  header: Authorization
  prefix: Bearer
  token:
    access-expiration-time: 3600000         # 1시간 3600000 # 3분 180000
    refresh-expiration-time: 2592000000     # 30 일 2592000000 # 1시간 3600000 # 3분 180000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#  datasource:
#    master:
#      hikari:
#        jdbc-url: jdbc:mysql://localhost:3306/payment
#        read-only: false
#        username: root
#        password: 1234
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    slave:
#      hikari:
#        jdbc-url: jdbc:mysql://localhost:3306/payment
#        read-only: true
#        username: root
#        password: 1234
#        driver-class-name: com.mysql.cj.jdbc.Driver